### ISSUE TITLE
Make delete idempotent

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ds-flatfs#30]
Currently, delete on a non-existent key returns `ErrNotFound`. However, this isn't really all that useful. Additionally,

1. badgerdb *doesn't* return an error when deleting a non-existent and making it do so will be a slight performance hit.
2. #27 will cause deletes to succeed, sometimes, even when there was no value to be deleted (e.g., a concurrent delete and put where we resolve the put *after* the delete).

**Comment by whyrusleeping** [comment]
hrm... I was against this until you threw my weakness at me. I love making things idempotent...

**Comment by kevina** [comment]
I think we should be what every in #27 is causing delete not to return the correct value.  I am against returning less information than we know.

At the specification level I would say that a datastore has the option of not returning `ErrNotFound`, but it should have the option to and if it does it should be reliable.

**Comment by Stebalien** [comment]
Moving to: https://github.com/ipfs/go-datastore/issues/104
