### ISSUE TITLE
User-friendly keys

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ds-flatfs#40]
Two proposals (assuming we don't deprecate this datastore soon):

1. Handle base32 encoding internally. Forcing the client to deal with filesystem name restrictions is painful and unnecessary.
2. Shard using a non-cryptographic hash function. We could, e.g., use SipHash (at most 50ns per hash versus 4000ns to open a file). Again, we shouldn't be making assumptions about keys specified by the user.

This way, we'd map `key` to `Base32(FastHash(key))[:2] + "/" + Base32(key)`.

**Comment by kevina** [comment]
We originally used binary keys and encoded to base16 in flatfs and had binary keys, that created some serious problems, see https://github.com/ipfs/go-ipfs/issues/2601 for context.

**Comment by Stebalien** [comment]
Well, yes, we shouldn't be mangling keys. I'd just treat them as byte strings.

**Comment by kevina** [comment]
The problem was that we use '/' as a path separator in datastore keys, that does not mix well when the key itself in binary, so we changed from using binary keys to text and encoded them to base32 before converting them to datastore keys.

**Comment by Stebalien** [comment]
Not sure if I understand. The `/` path separator used in *keys* shouldn't be reflected on-disk.

**Comment by aschmahmann** [comment]
Looks like this was closed by @Stebalien in #64
