### ISSUE TITLE
Consider using the last N digits instead of the first N for sharding.

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ds-flatfs#5]
With the way Cid's are structured the last bits are for more random with the first, although it may be unconventional, it will make more sense to using the last N digits instead of the first.

**Comment by kevina** [comment]
The other alternative is to do something dynamic which will be for more involved.

**Comment by whyrusleeping** [comment]
We're opting to use the last few characters for now, and moving towards a dynamic solution in the future. I think this can be closed now

**Comment by diasdavid** [comment]
Wait, so does this mean that now the repo will have to be migrated to use the last bits?
